# fly.toml app configuration file generated for anizavr on 2023-08-04T13:40:23+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "anizavr"
primary_region = "waw"

[build]


[[mounts]]
  source = "sqlite"
  destination = "/Database"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
